from __future__ import annotations

CEFR_LEVELS: tuple[str, ...] = ("A1", "A2", "B1", "B2", "C1", "C2")
DEFAULT_LEVEL = "B1"
MAX_DIFFICULT_WORDS = 8
LONG_WORD_LENGTH = 7
LONG_SENTENCE_WORD_COUNT = 18

COMMON_WORDS: set[str] = {
	"a",
	"about",
	"after",
	"again",
	"all",
	"also",
	"an",
	"and",
	"any",
	"are",
	"as",
	"at",
	"be",
	"because",
	"but",
	"by",
	"can",
	"could",
	"did",
	"do",
	"does",
	"each",
	"for",
	"from",
	"get",
	"go",
	"had",
	"has",
	"have",
	"he",
	"her",
	"here",
	"him",
	"his",
	"i",
	"if",
	"in",
	"into",
	"is",
	"it",
	"its",
	"just",
	"like",
	"me",
	"more",
	"most",
	"my",
	"no",
	"not",
	"now",
	"of",
	"on",
	"one",
	"or",
	"our",
	"out",
	"said",
	"see",
	"she",
	"should",
	"so",
	"some",
	"than",
	"that",
	"the",
	"their",
	"them",
	"then",
	"there",
	"these",
	"they",
	"this",
	"to",
	"two",
	"up",
	"us",
	"use",
	"was",
	"we",
	"were",
	"what",
	"when",
	"where",
	"which",
	"who",
	"will",
	"with",
	"would",
	"you",
	"your",
}

VOCABULARY_BANK: dict[str, dict[str, list[str] | str]] = {
	"abstract": {"meaning": "not connected to a concrete example", "synonyms": ["general", "theoretical"]},
	"analysis": {"meaning": "a careful study of something", "synonyms": ["study", "review"]},
	"architecture": {"meaning": "the design or structure of a system", "synonyms": ["design", "structure"]},
	"approximately": {"meaning": "close to the exact amount", "synonyms": ["about", "nearly"]},
	"beneficial": {"meaning": "helpful or good", "synonyms": ["helpful", "useful"]},
	"complex": {"meaning": "made of many parts or difficult to understand", "synonyms": ["complicated", "detailed"]},
	"consequence": {"meaning": "the result of an action", "synonyms": ["result", "outcome"]},
	"considerable": {"meaning": "fairly large or important", "synonyms": ["large", "significant"]},
	"demonstrate": {"meaning": "to show clearly", "synonyms": ["show", "prove"]},
	"describe": {"meaning": "to explain what something is like", "synonyms": ["explain", "tell"]},
	"determine": {"meaning": "to find out or decide", "synonyms": ["decide", "find"]},
	"differentiate": {"meaning": "to tell things apart", "synonyms": ["distinguish", "separate"]},
	"efficient": {"meaning": "working well without wasting time or energy", "synonyms": ["effective", "useful"]},
	"evidence": {"meaning": "facts that support a point", "synonyms": ["proof", "support"]},
	"facilitate": {"meaning": "to make something easier", "synonyms": ["help", "ease"]},
	"generate": {"meaning": "to create or produce", "synonyms": ["make", "produce"]},
	"important": {"meaning": "having a lot of value or meaning", "synonyms": ["key", "essential"]},
	"improve": {"meaning": "to make better", "synonyms": ["better", "upgrade"]},
	"information": {"meaning": "facts or details about something", "synonyms": ["details", "data"]},
	"integrate": {"meaning": "to combine into one system", "synonyms": ["combine", "join"]},
	"interpret": {"meaning": "to explain the meaning of something", "synonyms": ["explain", "read"]},
	"maintain": {"meaning": "to keep something in good condition", "synonyms": ["keep", "preserve"]},
	"necessary": {"meaning": "needed or required", "synonyms": ["needed", "required"]},
	"obtain": {"meaning": "to get or acquire", "synonyms": ["get", "receive"]},
	"objective": {"meaning": "a goal or purpose", "synonyms": ["goal", "aim"]},
	"proliferation": {"meaning": "a rapid increase in number", "synonyms": ["growth", "expansion"]},
	"progress": {"meaning": "movement toward a goal", "synonyms": ["advance", "improvement"]},
	"relevant": {"meaning": "closely connected to the topic", "synonyms": ["related", "important"]},
	"significant": {"meaning": "large enough to matter", "synonyms": ["important", "major"]},
	"significantly": {"meaning": "to a large degree or extent", "synonyms": ["greatly", "substantially"]},
	"strategy": {"meaning": "a plan for reaching a goal", "synonyms": ["plan", "approach"]},
	"subsequent": {"meaning": "coming after something else", "synonyms": ["next", "following"]},
	"transform": {"meaning": "to change from one form to another", "synonyms": ["change", "convert"]},
	"vocabulary": {"meaning": "the words known by a person", "synonyms": ["word list", "terms"]},
}

SIMPLIFICATION_MAP: dict[str, str] = {
	word: str(details["synonyms"][0]) for word, details in VOCABULARY_BANK.items()
}

